name: Water Watch CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install frontend dependencies
        working-directory: ./front-end
        run: npm install

      - name: Run frontend tests with increased memory
        working-directory: ./front-end
        run: node --max-old-space-size=8192 node_modules/.bin/vitest run

      - name: Build frontend
        working-directory: ./front-end
        run: npm run build

  build-and-test-backend:
    runs-on: ubuntu-latest
    needs: build-and-test-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js for back-end
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install backend dependencies
        working-directory: ./back-end
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: ${{ secrets.REPO_PATH }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REPO_PATH }}
            git pull origin main
            cd front-end
            sudo npm install
            sudo npm run build
            sudo systemctl restart nginx
